config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

  get 'projects/:project_id/fusion_billing(/:year(/:month))' => 'fusion_billing#index', as: 'fusion_billing_date'
  get 'projects/:project_id/fusion_invoicing(/:year/:month)(/:locale)' => 'fusion_invoicing#index', as: 'fusion_invoicing_date'

  get '/fusion_reports' => 'fusion_reports#index'

  get '/fusion_reports/revenue(/:year(/:month))' => 'fusion_reports#revenue', as: 'revenue_report'

  get '/fusion_reports/invoicing(/:year(/:month))' => 'fusion_reports#invoicing', as: 'fusion_invoicing_report'
  post '/fusion_reports/invoicing/:year/:month/new' => 'fusion_reports#create_invoices', as: 'fusion_invoicing_create_invoices'

  resources :projects do
    member do
      get 'fusion_billing'
      get 'fusion_invoicing'
    end
  end

app/models/fusion_invoicing.rb
class FusionInvoicing
  attr_accessor :financial_projects, :dates, :all_issues, :standing_issues, :non_invoiced_issues
  
  def initialize year, month
    @dates = create_date_range(year, month)

    @financial_projects = FusionInvoicingProject.invoicing

    @standing_issues = FusionInvoicingIssue.standing_financial_issues(@dates)
    @all_issues = FusionInvoicingIssue.all_financial_issues(@dates)

    @non_invoiced_issues = @all_issues.map{ |object|
      invoice = @standing_issues.where(subject: (object.subject + @dates.begin.strftime(" [%Y/%m]"))).first
      name = object.custom_values.where(custom_field_id: 86).first.value
      {
        project_id: object.project.id,
        financial_tracker: object.tracker.name,
        financial_subject: object.subject,
        financial_id: object.id,
        financial_start_date: object.start_date,
        financial_due_date: object.due_date,
        financial_account_manager: name,
        financial_generate_next_invoice_after: ( Date.parse(object.custom_values.where(custom_field_id: 149).first.value) rescue @dates.begin.beginning_of_month ),
        invoice_tracker: (invoice ? invoice.tracker.name : nil),
        invoice_subject: (invoice ? invoice.subject : nil),
        invoice_id: (invoice ? invoice.id : nil),
      }
    }

    self
  end

  def create_date_range year, month, operator = nil, amount = 0
    year  = year  ? year.to_i   : Date.today.year
    month = month ? month.to_i  : Date.today.month
    start_date  = Date.new(year, month, 1)
    start_date  = start_date.send(operator, amount) if amount > 0
    end_date    = (start_date >> 1) - 1

    (start_date..end_date)
  end
end

app/controllers/fusion_invoicing_controller.rb
class FusionInvoicingController < FusionBillingController
  unloadable
end

app/views/fusion_invoicing/_address_la.html.erb
<h3>Fusion Systems North America</h3>

<address>
  19191 S. Vermont Ave. Suite 820<br>
  Torrance, CA 90502 United States<br>
  +1 310 602 5140<br>
  billing@fusionsystems.org
</address>

app/views/fusion_invoicing/_address_sh.html.erb
<h3>Fusion Systems Shanghai</h3>

<address>
  14B1, CATIC Building<br>
  212 Jiangning Rd<br>
  Shanghai 200041 PRC<br>
  +86 21 5289 5858<br>
  billing@fusionsystems.org<br>
</address>

app/views/fusion_invoicing/_address_tk.html.erb
<h3>Fusion Systems Japan K.K.</h3>

<address>
  Daiwa Azabudai Building, Azabudai 2-3-3<br>
  Minato-ku, Tokyo 106-0041 Japan<br>
  +81 3 3505 2880<br>
  billing@fusionsystems.co.jp<br>
</address>

app/views/fusion_invoicing/_entry_table.html.erb
<% if entries.present? %>
  <table class="entry-table">
    <thead>
      <tr>
        <td class="entry-date">Date</td>
        <td class="entry-in-charge">In Charge</td>
        <td class="entry-tracker">Tracker</td>
        <td class="entry-activity">Activity</td>
        <td class="entry-comments">Comments</td>
        <td class="entry-hours">Hours</td>
      </tr>
    </thead>
    <tbody>
      <% entries.sort_by{ |id, hash| hash[:date] }.each do |id, hash| %>
        <tr class="<%= hash[:standard] == 0 && hash[:billable] == 1 ? "non-standard" : ""  %>">
          <td class="entry-date"><%= hash[:date] %></td>
          <td class="entry-in-charge"><%= hash[:in_charge] %></td>
          <td class="entry-tracker"><%= hash[:tracker] %></td>
          <td class="entry-activity"><%= hash[:activity] %></td>
          <td class="entry-comments"><%= hash[:comments] %></td>
          <td class="entry-hours"><%= hash[:hours] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="center">No Activity</h3>
<% end %>

app/views/fusion_invoicing/_invoice_fixed_line_items.html.erb
<table id="invoice-line-items">
  <thead>
    <tr>
      <td class="invoice-service">Service</td>
      <td class="invoice-hours">Hours</td>
      <td class="invoice-rate">Rate</td>
      <td class="invoice-line-total">Line Total</td>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td class="invoice-service">Service Fee</td>
      <td class="invoice-hours">-</td>
      <td class="invoice-rate">-</td>
      <td class="invoice-line-total"><%= number_to_currency(@billing.finance_issue.value_to_fusion_once_off, locale: @billing.finance_issue.locale) %></td>
    </tr>

  </tbody>
</table>

<div id="line-items-totals" class="group">
  <div id="sub-total">
    <span class="row-left">
      Sub total:
    </span>
    <span class="row-right">
      <%= number_to_currency(@billing.finance_issue.value_to_fusion_once_off, locale: @billing.finance_issue.locale) %>
    </span>
  </div>
  <% if @billing.finance_issue.location == "TK" %>
    <div id="tax-rate">
      <span class="row-left">
        Tax (<%= @billing.finance_issue.tax_rate %>)
      </span>
      <span class="row-right">
        <%= number_to_currency(@billing.current_entries.fixed_tax, locale: @billing.finance_issue.locale ) %>
      </span>
    </div>
  <% end %>
  <div id="total-charge">
    <span class="row-left">
      Total
    </span>
    <span class="row-right">
      <%= number_to_currency((@billing.current_entries.fixed_charge + @billing.current_entries.fixed_tax), locale: @billing.finance_issue.locale ) %>
    </span>
  </div>
</div>

app/views/fusion_invoicing/_invoice_fixed_synthetic.html.erb
<h2 class="center">Fixed (synthetic) not implemented yet</h2>

app/views/fusion_invoicing/_invoice_maintenance_time_entries.html.erb
<%= render "entry_table", entries: @billing.current_entries.billable_entries %>

app/views/fusion_invoicing/_invoice_t_m.html.erb
<div id="invoice">

  <div id="address">
    <%= render "address_#{@billing.finance_issue.location.downcase}" %>
  </div>

  <div id="logo">
    <%= image_tag "fusion_systems_logo.png", plugin: "fusion_billing" %>
  </div>

  <div id="issue-date">
    <div class="row-left">
      Issue date:
    </div>
    <div class="row-right">
      <%= @billing.this_month.end.strftime("%d %b %Y") %>
    </div>
    <br>
    <div class="row-left">
      Invoice number: 
    </div>
    <div class="row-right">
      <%= @billing.current_entries.invoice_number %>
    </div>
  </div>

  <h1 id="title">
    Invoice
  </h1>

  <h1 id="client-name">
    <%= @billing.project.name.split(":")[0] %>
  </h1>

  <div id="job-name">
    <span class="row-left">
      Job name:
    </span>
    <span class="row-right">
      <%= @billing.project.name.split(":")[1] %>
    </span>
  </div>

  <div id="duration">
    <span class="row-left">
      Duration:
    </span>
    <span class="row-right">
      <%= @billing.this_month.begin.strftime("%d %b %Y") %> - <%= @billing.this_month.end.strftime("%d %b %Y") %>
    </span>
  </div>

  <% if @billing.finance_issue.contractual_hours.present? %>
    <div id="contractual-hours">
      <span class="row-left">
        Contractual hours:
      </span>
      <span class="row-right">
        <%= @billing.finance_issue.contractual_hours %>
      </span>
    </div>
  <% end %>

  <% if @billing.finance_issue.ignore_ro == "0" %>
    <div span="rollover_hours">
      <span class="row-left">
        Rollover hours:
      </span>
      <span class="row-right">
        <%= @billing.current_entries.rollover_hours %>
      </span>
    </div>
  <% end %>

  <h1 id="line-items-title">
    Description
  </h1>

  <div id="line-items" class="group">
    <%= render "invoice_t_m_line_items" %>
  </div>

  <h1 id="service-details-title">
    Service Details
  </h1>

  <div id="time-entries">
    <%= render "invoice_t_m_time_entries" %>
  </div>

  <div id="footer">
    <p>Thank you for using Fusion Systems Group. We appreciate your business.</p>
  </div>

</div>

app/views/fusion_invoicing/_invoice_t_m_line_items.html.erb
<table id="invoice-line-items">
  <thead>
    <tr>
      <td class="invoice-service">Service</td>
      <td class="invoice-hours">Hours</td>
      <td class="invoice-rate">Rate</td>
      <td class="invoice-line-total">Line Total</td>
    </tr>
  </thead>
  <tbody>

    <% @billing.current_entries.non_standard_hours_line_item.each do |line_item| %>
      <tr>
        <td class="invoice-service">Non-standard Business Hours:<br><%= line_item[0] %></td>
        <td class="invoice-hours"><%= line_item[1] %></td>
        <td class="invoice-rate"><%= number_to_currency(line_item[2], locale: @billing.finance_issue.locale) %></td>
        <td class="invoice-line-total"><%= number_to_currency(line_item[3], locale: @billing.finance_issue.locale) %></td>
      </tr>
    <% end if @billing.current_entries.non_standard_hours_line_item.present? %>

    <% @billing.current_entries.standard_hours_line_item.each do |line_item| %>
      <tr>
        <td class="invoice-service">Standard Business Hours:<br><%= line_item[0] %></td>
        <td class="invoice-hours"><%= line_item[1] %></td>
        <td class="invoice-rate"><%= number_to_currency(line_item[2], locale: @billing.finance_issue.locale) %></td>
        <td class="invoice-line-total"><%= number_to_currency(line_item[3], locale: @billing.finance_issue.locale) %></td>
      </tr>
    <% end if @billing.current_entries.standard_hours_line_item.present? %>

    <% @billing.current_entries.additional_services_line_item.each do |line_item| %>
      <tr>
        <td class="invoice-service">Service Fee:<br><%= line_item[0] %></td>
        <td class="invoice-hours"><%= line_item[1] %></td>
        <td class="invoice-rate"><%= line_item[2] %></td>
        <td class="invoice-line-total"><%= number_to_currency(line_item[3], locale: @billing.finance_issue.locale) %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<div id="line-items-totals" class="group">
  <div id="sub-total">
    <span class="row-left">
      Sub total:
    </span>
    <span class="row-right">
      <%= number_to_currency(@billing.current_entries.total_charge, locale: @billing.finance_issue.locale) %>
    </span>
  </div>
  <% if @billing.finance_issue.location == "TK" %>
    <div id="tax-rate">
      <span class="row-left">
        Tax (<%= @billing.finance_issue.tax_rate %>)
      </span>
      <span class="row-right">
        <%= number_to_currency(@billing.current_entries.tax, locale: @billing.finance_issue.locale ) %>
      </span>
    </div>
  <% end %>
  <div id="total-charge">
    <span class="row-left">
      Total
    </span>
    <span class="row-right">
      <%= number_to_currency((@billing.current_entries.total_charge + @billing.current_entries.tax), locale: @billing.finance_issue.locale ) %>
    </span>
  </div>
</div>

app/views/fusion_invoicing/_invoice_t_m_synthetic.html.erb
<div id="invoice">

  <div id="address">
    <%= render "address_#{@billing.finance_issue.location.downcase}" %>
  </div>

  <div id="logo">
    <%= image_tag "fusion_systems_logo.png", plugin: "fusion_billing" %>
  </div>

  <div id="issue-date">
    <div class="row-left">
      Issue date:
    </div>
    <div class="row-right">
      <%= @billing.this_month.end.strftime("%d %b %Y") %>
    </div>
    <br>
    <div class="row-left">
      Invoice number: 
    </div>
    <div class="row-right">
      <%= @billing.current_entries.invoice_number %>
    </div>
  </div>

  <h1 id="title">
    Invoice
  </h1>

  <h1 id="client-name">
    <%= @billing.project.name.split(":")[0] %>
  </h1>

  <div id="job-name">
    <span class="row-left">
      Job name:
    </span>
    <span class="row-right">
      <%= @billing.project.name.split(":")[1] %>
    </span>
  </div>

  <div id="duration">
    <span class="row-left">
      Duration:
    </span>
    <span class="row-right">
      <%= @billing.this_month.begin.strftime("%d %b %Y") %> - <%= @billing.this_month.end.strftime("%d %b %Y") %>
    </span>
  </div>

  <% if @billing.finance_issue.contractual_hours.present? %>
    <div id="contractual-hours">
      <span class="row-left">
        Contractual hours:
      </span>
      <span class="row-right">
        <%= @billing.finance_issue.contractual_hours %>
      </span>
    </div>
  <% end %>

  <% if @billing.finance_issue.ignore_ro == "0" %>
    <div span="rollover_hours">
      <span class="row-left">
        Rollover hours:
      </span>
      <span class="row-right">
        <%= @billing.current_entries.rollover_hours %>
      </span>
    </div>
  <% end %>

  <h1 id="line-items-title">
    Description
  </h1>

  <div id="line-items" class="group">
    <%= render "invoice_t_m_synthetic_line_items" %>
  </div>

  <h1 id="service-details-title">
    Service Details
  </h1>

  <div id="time-entries">
    <%= render "invoice_t_m_synthetic_time_entries" %>
  </div>

</div>

app/views/fusion_invoicing/_invoice_t_m_synthetic_line_items.html.erb
<table id="invoice-line-items">
  <thead>
    <tr>
      <td class="invoice-service">Service</td>
      <td class="invoice-hours">Hours</td>
      <td class="invoice-rate">Rate</td>
      <td class="invoice-line-total">Line Total</td>
    </tr>
  </thead>
  <tbody>

    <% @billing.current_entries.standard_hours_line_item.each do |line_item| %>
      <tr>
        <td class="invoice-service">Standard Business Hours:<br><%= line_item[0] %></td>
        <td class="invoice-hours"><%= line_item[1] %></td>
        <td class="invoice-rate"><%= number_to_currency(@billing.finance_issue.fsg_billable_rate, locale: @billing.finance_issue.locale) %></td>
        <td class="invoice-line-total"><%= number_to_currency(@billing.current_entries.fsg_charge, locale: @billing.finance_issue.locale) %></td>
      </tr>
    <% end if @billing.current_entries.standard_hours_line_item.present? %>

  </tbody>
</table>

<div id="line-items-totals" class="group">
  <div id="sub-total">
    <span class="row-left">
      Sub total:
    </span>
    <span class="row-right">
      <%= number_to_currency(@billing.current_entries.fsg_charge, locale: @billing.finance_issue.locale) %>
    </span>
  </div>
  <% if @billing.finance_issue.location == "TK" %>
    <div id="tax-rate">
      <span class="row-left">
        Tax (<%= @billing.finance_issue.tax_rate %>)
      </span>
      <span class="row-right">
        <%= number_to_currency(@billing.current_entries.fsg_tax, locale: @billing.finance_issue.locale ) %>
      </span>
    </div>
  <% end %>
  <div id="total-charge">
    <span class="row-left">
      Total
    </span>
    <span class="row-right">
      <%= number_to_currency((@billing.current_entries.fsg_total_charge + @billing.current_entries.tax), locale: @billing.finance_issue.locale ) %>
    </span>
  </div>
</div>

app/views/fusion_invoicing/_invoice_t_m_time_entries.html.erb
<%= render "entry_table", entries: @billing.current_entries.billable_entries %>

app/views/fusion_invoicing/_locales.html.erb
<div id="locale-links" class="center">
  <%= link_to "JPY", fusion_invoicing_date_path(@billing.project, params[:year], params[:month], :ja), class: (@billing.finance_issue.locale == "ja" ? 'active' : '') %>
  <%= link_to "HKD", fusion_invoicing_date_path(@billing.project, params[:year], params[:month], "zh-HK"), class: (@billing.finance_issue.locale == "zh-HK" ? 'active' : '') %>
  <%= link_to "CNY", fusion_invoicing_date_path(@billing.project, params[:year], params[:month], "zh-CN"), class: (@billing.finance_issue.locale == "zh-CN" ? 'active' : '') %>
  <%= link_to "USD", fusion_invoicing_date_path(@billing.project, params[:year], params[:month], :en), class: (@billing.finance_issue.locale == "en" ? 'active' : '') %>
</div>

app/views/fusion_invoicing/index.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'billing', plugin: 'fusion_billing' %>
  <%= stylesheet_link_tag 'invoice_print', plugin: 'fusion_billing', media: 'print' %>
<% end %>

<% current_locale = params[:locale] || :en %>

<h2 id="project-name" class="center"><%= @billing.project.name %></h2>

<h3 id="title-date" class="center date"><%= render "date" unless @billing.errors.present? || @billing.sub_projects.present? || (!@billing.finance_issue.nil? && @billing.finance_issue.sow_type == "Fixed") %></h3>

<%= render "navigation" unless @billing.errors.present? || @billing.sub_projects.present? || (!@billing.finance_issue.nil? && @billing.finance_issue.sow_type == "Fixed") %>

<%= render "locales" if @billing.sub_projects.empty? && @billing.errors.empty? %>

<%= render "tree" if @billing.sub_projects.present? %>

<%= render "errors" if @billing.errors.present? %> 

<%= render "invoice_#{@billing.finance_issue.sow_type.parameterize.underscore}#{@billing.finance_issue.synthetic == "1" ? "_synthetic" : "" }" unless @billing.errors.present? || @billing.finance_issue.nil? || @billing.sub_projects.present? %>

<div id="real-time-entry-table">
  <%= render "entry_table", entries: @billing.current_entries.billable_entries unless @billing.errors.present? || @billing.finance_issue.nil? || @billing.sub_projects.present? || @billing.finance_issue.sow_type == "Fixed" %>
</div>