config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

  get 'projects/:project_id/fusion_billing(/:year(/:month))' => 'fusion_billing#index', as: 'fusion_billing_date'
  get 'projects/:project_id/fusion_invoicing(/:year/:month)(/:locale)' => 'fusion_invoicing#index', as: 'fusion_invoicing_date'

  get '/fusion_reports' => 'fusion_reports#index'

  get '/fusion_reports/revenue(/:year(/:month))' => 'fusion_reports#revenue', as: 'revenue_report'

  get '/fusion_reports/invoicing(/:year(/:month))' => 'fusion_reports#invoicing', as: 'fusion_invoicing_report'
  post '/fusion_reports/invoicing/:year/:month/new' => 'fusion_reports#create_invoices', as: 'fusion_invoicing_create_invoices'

  resources :projects do
    member do
      get 'fusion_billing'
      get 'fusion_invoicing'
    end
  end

app/controllers/fusion_reports_controller.rb
class FusionReportsController < ApplicationController
  before_filter :require_admin

  def index
  end

  def revenue
    @report = FusionRevenue.new(params)

    respond_to do |format|
      format.html
      format.csv { send_data(@report.to_csv, filename: "revenue.csv") }
    end

  end

  def invoicing
    @report = FusionInvoicing.new(params[:year], params[:month])
  end

  def create_invoices
    @report = FusionInvoicing.new(params[:year], params[:month])
    @standing_issues = @report.standing_issues
    !params[:projects].nil? && params[:projects].each do |issue_name, project|
      begin
      project = eval(project)
      issue = Issue.create!(
        project_id: project[:project_id],
        subject: "#{issue_name}#{@report.dates.begin.strftime(" [%Y/%m]")}",
        start_date: @report.dates.begin,
        tracker_id: Tracker.where(id: 62).first,
        author: User.find(222),
        priority: IssuePriority.where(name: 'Normal').first,
        description: "This issue was created by the Fusion Billing plugin.\n\"Billing\":#{url_for(controller: 'fusion_billing', action: 'index', project_id: Project.where(name: issue_name, status: 1).first.identifier, year: @report.dates.begin.year, month: @report.dates.begin.month)}\n\"Invoicing\":#{url_for(controller: 'fusion_invoicing', action: 'index', project_id: Project.where(name: issue_name, status: 1).first.identifier, year: @report.dates.begin.year, month: @report.dates.begin.month)}",
        custom_values: [CustomValue.new(custom_field_id: 86, value: project[:financial_account_manager])]
      ) if Issue.where(subject: issue_name + @report.dates.begin.strftime(" [%Y/%m]")).empty?
      rescue
        raise "Error with #{issue_name}"
      end
    end
    redirect_to(fusion_invoicing_report_path(year: @report.dates.begin.year, month: @report.dates.begin.month), notice: "Issues created")
  end

end

app/views/fusion_reports/_sidebar.html.erb
<h3>Reports</h3>

<ul class="queries">

  <li class="query">
    <%= link_to "Revenue", revenue_report_path %>
  </li>

  <li class="query">
    <%= link_to "Invoicing", fusion_invoicing_report_path %>
  </li>

</ul>

app/views/fusion_reports/index.html.erb
<h2 class="center">Fusion Reports</h2>

<%= render "sidebar" %>

app/views/fusion_reports/invoicing.html.erb
<% content_for :header_tags do %>
  <%= javascript_include_tag :fusion_invoicing, plugin: 'fusion_billing' %>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

<h2>Invoicing report</h2>

<%= render "fusion_reports/invoicing/navigation" %>

<%= form_tag(fusion_invoicing_create_invoices_path(params[:year] || Date.today.year, params[:month] || Date.today.month), method: :post)  do %>
  <table id="invoicing-issues">
    <thead>
      <tr>
        <td>Tracker</td>
        <td>Start date</td>
        <td>Due date</td>
        <td><%= check_box_tag :check_all %></td>
        <td>Finance issue</td>
        <td>Invoice issue</td>
      </tr>
    </thead>
    <tbody>
      <% @report.non_invoiced_issues.each do |item| %>
        <tr>
          <td><%= item[:financial_tracker] %></td>
          <td><%= item[:financial_start_date] %></td>
          <td><%= item[:financial_due_date] %></td>
          <td><%= check_box_tag "projects[#{item[:financial_subject]}]", "{project_id: #{item[:project_id]}, financial_account_manager: '#{item[:financial_account_manager]}'}", (((item[:financial_tracker] == "Support" && item[:financial_generate_next_invoice_after] <= @report.dates.begin) && item[:invoice_id].nil?) || (item[:financial_tracker] == "Delivery" && @report.dates.include?(item[:financial_due_date]))), class: "create-invoice-checkbox" %></td>
          <td><%= link_to item[:financial_subject], issue_path(item[:financial_id]) %></td>
          <td><%= link_to item[:invoice_subject], issue_path(item[:invoice_id]) unless item[:invoice_id].nil? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <button class="button create-invoices">Create Invoices</button>
<% end %>

app/views/fusion_reports/revenue.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'reports_revenue', plugin: 'fusion_billing' %>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

<h2 class="center">Revenue report</h2>

<%= render "fusion_reports/revenue/navigation" %>

<%= link_to "Download CSV", revenue_report_path(format: 'csv') %>

<table id="revenue_table">
  <thead>
    <tr>
      <td>Project</td>
      <td>SOW Type</td>
      <td>Beginning Date</td>
      <td>End Date</td>
      <td>Revenue</td>
    </tr>
  </thead>
  <tbody>
    <% @report.itms_projects.each do |itms_project| %>
      <tr>
        <td><%= itms_project.name %></td>
        <td><%= itms_project.finance_issue.instance_variable_get("@sow_type") %></td>
        <td><%= itms_project.beginning_date %></td>
        <td><%= itms_project.end_date %></td>
        <td><%= itms_project.total_charge %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# debug @report.finance_issues %>
<%# debug @report.finance_issue_subjects %>
<%# debug @report.get_itms_projects %>