config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

  get 'projects/:project_id/fusion_billing(/:year(/:month))' => 'fusion_billing#index', as: 'fusion_billing_date'
  get 'projects/:project_id/fusion_invoicing(/:year/:month)(/:locale)' => 'fusion_invoicing#index', as: 'fusion_invoicing_date'

  get '/fusion_reports' => 'fusion_reports#index'

  get '/fusion_reports/revenue(/:year(/:month))' => 'fusion_reports#revenue', as: 'revenue_report'

  get '/fusion_reports/invoicing(/:year(/:month))' => 'fusion_reports#invoicing', as: 'fusion_invoicing_report'
  post '/fusion_reports/invoicing/:year/:month/new' => 'fusion_reports#create_invoices', as: 'fusion_invoicing_create_invoices'

  resources :projects do
    member do
      get 'fusion_billing'
      get 'fusion_invoicing'
    end
  end

app/models/fusion_billing.rb
class FusionBilling
  attr_reader :errors, :project, :sub_projects, :finance_issue, :current_entries, :previous_entries

  attr_accessor :last_month, :this_month

  def initialize project_id, locale = nil, year = nil, month = nil
    @errors = []

    @project = FusionBillingProject.this_project(project_id)
    @sub_projects = FusionBillingProject.sub_projects(@project)

    return unless @sub_projects.empty?

    self.send("this_month=", create_date_range(year, month))
    self.send("last_month=", create_date_range(year, month, :<<, 1))
 
    @finance_issue = FusionBillingIssue.finance_issue(@project).first
    if @finance_issue.nil?
      raise "No finance issue found"
    end
    @finance_issue = @finance_issue.format_issue(locale, @last_month, @this_month)

    @previous_entries = FusionBillingTimeEntry.new(@project, @last_month, @finance_issue)
    @current_entries = FusionBillingTimeEntry.new(@project, @this_month, @finance_issue, @previous_entries)

  rescue => error

    puts "====='error'=====\n#{error}\n==========\n"
    @errors.push(error)

  end

  def create_date_range year, month, operator = nil, amount = 0
    year  = year  ? year.to_i   : (Date.today.beginning_of_month << 1).year
    month = month ? month.to_i  : (Date.today.beginning_of_month << 1).month
    start_date  = Date.new(year, month, 1)
    start_date  = start_date.send(operator, amount) if amount > 0
    end_date    = (start_date >> 1) - 1

    (start_date..end_date)
  end

end

app/controllers/fusion_billing_controller.rb
class FusionBillingController < ApplicationController
  unloadable
  before_filter :find_project, :authorize, :only => :index

  def index
    @billing = FusionBilling.new(params[:project_id], params[:locale], params[:year], params[:month])
    respond_to do |format|
      format.html
      format.csv { send_data(@billing.current_entries.to_csv, filename: "billing_#{@billing.project.name.parameterize.underscore}.csv") }
    end
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

end

app/views/fusion_billing/_entry_table.html.erb
<% content_for :header_tags do %>
  <%= javascript_include_tag :fusion_billing, plugin: 'fusion_billing' %>
<% end %>

  <table class="entry-table">
    <thead>
      <tr>
        <td class="entry-date">Date</td>
        <td class="entry-in-charge">In Charge</td>
        <td class="entry-tracker">Tracker</td>
        <td class="entry-activity">Activity</td>
        <td class="entry-comments">Comments</td>
        <td class="entry-hours">Hours</td>
        <td class="entry-charge">Charge</td>
      </tr>
    </thead>
    <tbody>
      <% entries.sort_by{ |id, hash| hash[:date] }.each do |id, hash| %>
        <tr data-link="<%= edit_time_entry_path(id) %>"  class="<%= hash[:standard] == 0 && hash[:billable] == 1 ? "non-standard" : ""  %>">
          <td class="entry-date"><%= hash[:date] %></td>
          <td class="entry-in-charge"><%= hash[:in_charge] %></td>
          <td class="entry-tracker"><%= hash[:tracker] %></td>
          <td class="entry-activity"><%= hash[:activity] %></td>
          <td class="entry-comments"><%= hash[:comments] %></td>
          <td class="entry-hours"><%= hash[:hours] %></td>
          <td class="entry-charge"><%= hash[:charge] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/fusion_billing/_errors.html.erb
  <% @billing.errors.each do |error| %>
    <div class="center"><h2><%= error %></h2></div>
  <% end %>

app/views/fusion_billing/_fixed.html.erb
<%= render 'navigation' %>

<%= render "fixed_equation" %>

<%= link_to "Download CSV", fusion_billing_date_path(year: params[:year], month: params[:month], format: "csv") unless @billing.current_entries.empty? %>

<%= render "entry_table", entries: @billing.current_entries.billable_entries %>

app/views/fusion_billing/_fixed_equation.html.erb
<div class="summary center">

  <div class="summary-box">
    <div class="summary-title">Total hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.total_hours, precision: 2, delimiter: "," ) %></div>
  </div>

</div>

app/views/fusion_billing/_maintenance.html.erb
<h3>Maintenance template</h3>

app/views/fusion_billing/_manual.html.erb
<%= render "navigation" %>

<%= render (@billing.finance_issue.ignore_ro == "1" || @billing.finance_issue.ignore_ro.nil? ? "without_rollover" : "with_rollover") %>

<div class="charges center">

  <div class="standard-charge">
    Standard charge: <%= number_with_precision(@billing.current_entries.standard_charge, precision: 2, delimiter: "," ) %>
  </div>

  <div class="non-standard-charge">
    Non-standard charge: <%= number_with_precision(@billing.current_entries.non_standard_charge, precision: 2, delimiter: "," ) %>
  </div>

  <div class="contractual-charge">
    Contractual charge: <%= number_with_precision(@billing.current_entries.contractual_charge, precision: 2, delimiter: "," ) %>
  </div>

  <div class="additional-charge">
    Additional charge: <%= number_with_precision(@billing.finance_issue.additional_service_fees, precision: 2, delimiter: "," ) %>
  </div>

  <div class="total-charge">
    Total charge: <%= number_with_precision(@billing.current_entries.total_charge, precision: 2, delimiter: "," ) %>
  </div>

</div>

<%= link_to "Download CSV", fusion_billing_date_path(year: params[:year], month: params[:month], format: "csv") unless @billing.current_entries.empty? %>

<%= render "entry_table", entries: @billing.current_entries.billable_entries %>
<%= render "entry_table", entries: @billing.current_entries.non_billable_entries %>

app/views/fusion_billing/_navigation.html.erb
<% current_date = Date.new(
  params[:year].nil? ? (Date.today.beginning_of_month << 1 ).year : params[:year].to_i,
  params[:month].nil? ? (Date.today.beginning_of_month << 1 ).month : params[:month].to_i,
  1) %>

<% next_month = current_date >> 1 %>

<% last_month = current_date << 1 %>

<div class="navigation-container center group">
  <%= link_to content_tag(:span, "&lang;".html_safe, class: "link-angle"), fusion_billing_date_path(@project, last_month.year, last_month.month), class: "previous-link" %>

  <%= link_to content_tag(:span, "&rang;".html_safe, class: "link-angle"), fusion_billing_date_path(@project, next_month.year, next_month.month), class: "next-link" %>

  <span class="years-span">
    <% ((Date.today.year - 5)..Date.today.year).each do |year| %>
      <%= link_to content_tag(:span, year, class: "year-link #{year == current_date.year ? 'active' : ''}"), fusion_billing_date_path(@project, year, current_date.month) %>
    <% end %>
  </span>

  <span class="months-span">
    <% (1..12).each do |month| %>
      <%= link_to content_tag(:span, month, class: "month-link #{month == current_date.month ? 'active' : ''}"), fusion_billing_date_path(@project, current_date.year, month) %>
    <% end %>
  </span>

</div>

app/views/fusion_billing/_rollover.html.erb
<div class="summary center">
  (
  <div class="summary-box">
    <div class="summary-title">Contractual hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.finance_issue.contractual_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  -
  <div class="summary-box">
    <div class="summary-title">Standard hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.standard_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  =
  <div class="summary-box">
    <div class="summary-title">Rollover hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.rollover_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  )
</div>

app/views/fusion_billing/_sow_type.html.erb
( <%= @billing.finance_issue.present? && @billing.finance_issue.sow_type.present? ? @billing.finance_issue.sow_type : "sow inaccessible" %> )

app/views/fusion_billing/_t_m_synthetic.html.erb
<%= render "navigation" %>

<div class="summary center">
  <div class="summary-box">
    <div class="summary-title">Billable hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.billable_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  +
  <div class="summary-box">
    <div class="summary-title">Non-billable hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.non_billable_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  =
  <div class="summary-box">
    <div class="summary-title">Total hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.total_hours, precision: 2, delimiter: "," ) %></div>
  </div>
</div>

<%= render "rollover" unless @billing.finance_issue.ignore_ro == "1" %>

<div class="charges center">
  <div class="total-charge">
    Total charge: <%= number_with_precision(@billing.current_entries.fsg_charge, precision: 2, delimiter: "," ) %>
  </div>
</div>

<%= link_to "Download CSV", fusion_billing_date_path(year: params[:year], month: params[:month], format: "csv") unless @billing.current_entries.empty? %>

<%= render "entry_table", entries: @billing.current_entries.billable_entries %>
<%= render "entry_table", entries: @billing.current_entries.non_billable_entries %>

app/views/fusion_billing/_tree.html.erb
<% @billing.sub_projects.each do |project| %>
  <div><%= link_to project, fusion_billing_project_path(project) %></div>
<% end %>

app/views/fusion_billing/_with_rollover.html.erb
<div class="summary center">
  ((
  <div class="summary-box">
    <div class="summary-title">Standard hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.standard_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  -
  <div class="summary-box">
    <div class="summary-title">Rolled-over hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.previous_entries.rollover_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  )
  +
  <div class="summary-box">
    <div class="summary-title">Non-standard hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.non_standard_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  =
  <div class="summary-box">
    <div class="summary-title">Billable hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.billable_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  )
  +
  <div class="summary-box">
    <div class="summary-title">Non-billable hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.non_billable_hours, precision: 2, delimiter: "," ) %></div>
  </div>
  =
  <div class="summary-box">
    <div class="summary-title">Total hours:</div>
    <div class="summary-content"><%= number_with_precision(@billing.current_entries.total_hours, precision: 2, delimiter: "," ) %></div>
  </div>
</div>